apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nettols
  name: nettols
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: rtsp/net-tools
    name: nettols
    resources: {}
    volumeMounts:
    - name: ca-cert
      mountPath: /etc/ssl/certs/trust-bundle.pem
      subPath: trust-bundle.pem
      readOnly: true
  volumes:
  - name: ca-cert
    configMap:
      name: trust-ca
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}