kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-db
provisioner: driver.longhorn.io 
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fsType: "ext4"
  diskSelector: "ssd"
  nodeSelector: "db"

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-data
provisioner: driver.longhorn.io 
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fsType: "ext4"
  diskSelector: "hdd"
  nodeSelector: "data"
