apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
  labels:
    app: alertmanager
spec:
  project: monitoring
  sources:
  - repoURL: https://github.com/vladoz77/k8s-applications.git
    targetRevision: HEAD 
    path: victoria-metrics-monitoring/alertmanager/manifests
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
