apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
  labels:
    app: monitoring
spec:
  project: monitoring
  source:
    repoURL: 'https://github.com/vladoz77/argocd'
    path: monitoring/kube-state-metrics
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
