apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vmalert
  namespace: argocd
  labels:
    app: monitoring
spec:
  project: monitoring
  source:
    repoURL: 'https://github.com/vladoz77/k8s.git'
    path: monitoring/vmalert
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
