apiVersion: v1
kind: ServiceAccount
metadata:
  name: production-secrets
  namespace: production

---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend-2
  namespace: production
spec:
  provider:
    vault:
      server: "https://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      caProvider:
        type: ConfigMap
        name: trust-ca
        key: trust-bundle.pem
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "production-secrets"
          serviceAccountRef:
            name: production-secrets