apiVersion: v1
kind: Namespace
metadata:
  name: production

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: production-sa
  namespace: production

---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend-production
  namespace: production
spec:
  provider:
    vault:
      server: "https://vault.vault.svc.cluster.local:8200"
      path: production
      version: "v2"
      caProvider:
        type: ConfigMap
        name: trust-ca
        key: trust-bundle.pem
      auth:
        kubernetes:
          mountPath: kubernetes
          role: production-secrets
          serviceAccountRef:
            name: production-sa