apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-secret
  name: test-secret
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-secret
  template:
    metadata:
      labels:
        app: test-secret
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        env:
        - name: pg_connections
          valueFrom:
            secretKeyRef:
              name: database-connection
              key: connection_string
        volumeMounts:
        - name: db-config
          mountPath: /app/config.json   
          subPath: config.json          
          readOnly: true
      volumes:
      - name: db-config
        secret:
          secretName: database-connection
