apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-writer
  namespace: monitoring
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-writer
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-writer
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-writer
subjects:
- kind: ServiceAccount
  name: secrets-writer
---
apiVersion: batch/v1
kind: Job
metadata:
  name: secret-writer
  namespace: monitoring
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccount: secrets-writer
      serviceAccountName: secrets-writer
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      automountServiceAccountToken: true
      containers:
      - image: bitnami/kubectl
        command: [ "/bin/sh" ]
        args:
        - "-c"
        - >
          kubectl create secret generic etcd-secrets --dry-run=client \
              --from-file=/etc/kubernetes/pki/etcd/ca.crt \
              --from-file=/etc/kubernetes/pki/etcd/server.crt \
              --from-file=/etc/kubernetes/pki/etcd/server.key -o yaml \
              -n monitoring | kubectl apply -f -
        imagePullPolicy: IfNotPresent
        name: kubectl
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /etc/kubernetes/pki/etcd
          name: k8setcdcert
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: tmp
        emptyDir: {}
      - hostPath:
          path: /etc/kubernetes/pki/etcd
        name: k8setcdcert
