apiVersion: v1
kind: Namespace
metadata:
  name: db

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc-headless
  namespace: db
spec:
  clusterIP: None
  selector:
    app: postgresql-app
  ports:
  - port: 5432
    targetPort: psql

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc
  namespace: db
spec:
  type: NodePort
  selector:
    app: postgresql-app
  ports:
  - port: 5432
    targetPort: psql
    nodePort: 32543

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-sts
  namespace: db
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  selector:
    matchLabels:
      app: postgresql-app
  serviceName: postgresql-svc-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-app
    spec:
      containers:
      - name: postgresql
        image: postgres:18.4
        env:
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: password
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          runAsGroup: 999
        resources:
          requests:
            memory: "265Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
          name: psql
        volumeMounts:
        - name: db
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready -h localhost -p 5432 -U postgres
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready -h localhost -p 5432 -U postgres
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-external-secret
  namespace: db
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: infra-vault-backend
    kind: ClusterSecretStore
  target:
    name: pg-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: postgres
      property: username
  - secretKey: password
    remoteRef:
      key: postgres
      property: password
