apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
type: Opaque
data:
  rootUser: YWRtaW4K
  rootPassword: cGFzc3dvcmQK
  lokiPassword: cGFzc3dvcmQK
  tempoPassword: cGFzc3dvcmQK
