apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: vm
  namespace: monitoring
spec:
  image:
    tag: v1.96.0
  extraArgs:
    http.pathPrefix: /vmalert
  replicaCount: 1
  # logFormat: json
  datasource:
    url: "http://vmsingle-vm.monitoring.svc:8429/vm"
  notifier:
    url: "http://vmalertmanager-vm.monitoring.svc:9093"
  remoteWrite:
    url: "http://vmsingle-vm.monitoring.svc:8429/vm"
  evaluationInterval: "30s"
  selectAllByDefault: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

