fullnameOverride: authentik

global:
  image:
    repository: ghcr.io/goauthentik/server
    tag: ""

authentik:
  log_level: info
  secret_key: fWQcmeVjo5YBLkztkyrbkQfoOJN2judnnFoq239v8biFkcOJ/MRKtS6iYdrPA2C8/r3kpHWV3qBOL8MU
  
  email:
    host: smtp.gmail.com
    port: 465
    username: vladozz23@gmail.com
    password: irjckbsajihmbpjq
    use_ssl: true
    from: authentik@gmail.com
    
  postgresql:
    host: postgresql-svc.db.svc
    name: authentik-db
    user: authentik
    password: password

server:
  replicas: 1
  
  volumeMounts:
    - name: media-volume
      mountPath: /media

  volumes: 
    - name: media-volume
      persistentVolumeClaim:
        claimName: media-folder-pvc

  metrics:
    enabled: true
    service:
      annotations: {}
  ingress:
    enabled: true
    annotations: 
      cert-manager.io/cluster-issuer: ca-issuer
    hosts:
        - auth.dev.local
    tls:
      - secretName: authentik-tls
        hosts:
          - auth.dev.local

postgresql:
  enabled: false

redis:
  enabled: true

additionalObjects: 
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: media-folder-pvc
      namespace: auth
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      resources:
        requests:
          storage: 8Gi
      storageClassName: local-path