nameOverride: argocd
fullnameOverride: argocd

crds:
  keep: false

global:
  domain: argocd.dev.local
  logging:
    format: json
    level: info

configs:
  cm:
    application.resourceTrackingMethod: annotation
    controller.diff.server.side: "true"
  params:
    server.insecure: true
  secret:
    # htpasswd -nbBC 10 "" $ARGO_PWD | tr -d ':\n' | sed 's/$2y/$2a/'
    argocdServerAdminPassword: "$2a$10$S6gJky57fHflfWp7RC7Y6OLTN1I6VMRelH/jsNP3DCxOyVf5JVf9a"

controller:
  replicas: 1
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"

server:
  certificate:
    enabled: true
    domain: argocd.dev.local
    renewBefore: 360h
    duration: 9125h
    issuer:
      group: cert-manager.io
      kind: ClusterIssuer
      name: ca-issuer
    privateKey:
      algorithm: RSA
      encoding: PKCS8
      size: 4096
      rotationPolicy: Always
    usages:
    - server auth

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hostname: argocd.dev.local
    path: /
    pathType: Prefix
    tls: true
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8083"

repoServer:
  volumes:
  - name: ca-cert
    configMap:
      name: trust-ca
  volumeMounts:
  - name: ca-cert
    mountPath: /etc/ssl/certs/trust-bundle.pem
    subPath: trust-bundle.pem
    readOnly: true
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8084"

dex:
  enabled: false
