nameOverride: argocd
fullnameOverride: argocd

crds:
  keep: true

global:
  domain: argocd.dev.local
  logging:
    format: json
    level: info

configs:
  cm:
    # Disable admin user and use OIDC groups for RBAC instead
    admin.enabled: false
    url: https://argocd.dev.local
    application.resourceTrackingMethod: annotation
    controller.diff.server.side: "true"
    # OIDC configuration
    oidc.config: |
      name: authentik
      issuer: https://auth.dev.local/application/o/argocd/
      clientID: EbuwrFxswwoAqmGctCjHelyzRZ8hbKAKEsMYYZyb
      requestedScopes: ["openid", "profile", "email", "groups"]
      requestedIDTokenClaims: {"groups": {"essential": true}}
      enablePKCEAuthentication: true
      logoutURL: https://auth.dev.local/application/o/argocd/end-session/?id_token_hint={{token}}&post_logout_redirect_uri={{logoutRedirectURL}}

  params:
    server.insecure: true
  rbac:
    create: true
    # Need create groups ArgocdAdmins and ArgocdViewers in OIDC Provider
    policy.csv: |
      g, ArgoCD Admins, role:admin
      g, ArgoCD Viewers, role:readonly

controller:
  replicas: 1
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"

dex:
  enabled: false

server:
  volumes:
  - name: trust-ca
    configMap:
      name: trust-ca
  volumeMounts:
  - mountPath: /etc/ssl/certs/ca.pem
    name: trust-ca
    subPath: trust-bundle.pem
    readOnly: true
  httproute:
    enabled: true
    parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
      sectionName: https
      port: 443
    hostnames:
    - argocd.dev.local
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8083"

repoServer:
  volumes:
  - name: trust-ca
    configMap:
      name: trust-ca
  volumeMounts:
  - mountPath: /etc/ssl/certs/ca.pem
    name: trust-ca
    subPath: trust-bundle.pem
    readOnly: true
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8084"


redis:
  enabled: true
  image: 
    repository: redis
    tag: 8.2.3-alpine