apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-writer
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-writer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-writer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-writer
subjects:
- kind: ServiceAccount
  name: secrets-writer
---
apiVersion: batch/v1
kind: Job
metadata:
  name: secret-writer
spec:
  template:
    spec:
      automountServiceAccountToken: true
      containers:
      - image: docker.io/bitnami/kubectl:1.32.0-debian-12-r0
        command: [ "/bin/sh" ]
        args:
        - "-c"
        - >
          kubectl get secrets -n cert-manager ca-secret -o json | jq '.data."ca.crt"' | base64 -di > /tmp/ca.crt && kubectl create secret generic -n argocd ca-certs --from-file=ca.pem=/tmp/ca.crt
        imagePullPolicy: IfNotPresent
        name: kubectl
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 60
          seLinuxOptions: {}
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: tmp
        emptyDir: {}
      restartPolicy: Never
      serviceAccount: secrets-writer
      serviceAccountName: secrets-writer
  backoffLimit: 3
